const movies = [
  // English Movies
  {
    _id: "1",
    title: "Avengers: Endgame",
    genre: { name: "Action" },
    language: "English",
    numberInStock: 10,
    dailyRentalRate: 2.5,
  },
  {
    _id: "2",
    title: "The Hangover",
    genre: { name: "Comedy" },
    language: "English",
    numberInStock: 5,
    dailyRentalRate: 3.0,
  },
  {
    _id: "3",
    title: "La La Land",
    genre: { name: "Romance" },
    language: "English",
    numberInStock: 3,
    dailyRentalRate: 2.5,
  },
  {
    _id: "4",
    title: "The Dark Knight",
    genre: { name: "Thriller" },
    language: "English",
    numberInStock: 7,
    dailyRentalRate: 3.5,
  },

  // Hindi Movies
  {
    _id: "5",
    title: "Kabir Singh",
    genre: { name: "Action" },
    language: "Hindi",
    numberInStock: 7,
    dailyRentalRate: 2.0,
  },
  {
    _id: "6",
    title: "3 Idiots",
    genre: { name: "Comedy" },
    language: "Hindi",
    numberInStock: 5,
    dailyRentalRate: 2.5,
  },
  {
    _id: "7",
    title: "Dilwale Dulhania Le Jayenge",
    genre: { name: "Romance" },
    language: "Hindi",
    numberInStock: 4,
    dailyRentalRate: 2.0,
  },
  {
    _id: "8",
    title: "Talaash",
    genre: { name: "Thriller" },
    language: "Hindi",
    numberInStock: 6,
    dailyRentalRate: 3.0,
  },

  // Spanish Movies
  {
    _id: "9",
    title: "The Invisible Guest",
    genre: { name: "Action" },
    language: "Spanish",
    numberInStock: 8,
    dailyRentalRate: 2.8,
  },
  {
    _id: "10",
    title: "Ocho Apellidos Vascos",
    genre: { name: "Comedy" },
    language: "Spanish",
    numberInStock: 6,
    dailyRentalRate: 2.4,
  },
  {
    _id: "11",
    title: "The Secret Life of Pets",
    genre: { name: "Romance" },
    language: "Spanish",
    numberInStock: 5,
    dailyRentalRate: 2.7,
  },
  {
    _id: "12",
    title: "The Body",
    genre: { name: "Thriller" },
    language: "Spanish",
    numberInStock: 7,
    dailyRentalRate: 3.2,
  },

  // French Movies
  {
    _id: "13",
    title: "Lupin",
    genre: { name: "Action" },
    language: "French",
    numberInStock: 9,
    dailyRentalRate: 3.0,
  },
  {
    _id: "14",
    title: "Intouchables",
    genre: { name: "Comedy" },
    language: "French",
    numberInStock: 5,
    dailyRentalRate: 2.5,
  },
  {
    _id: "15",
    title: "Amour",
    genre: { name: "Romance" },
    language: "French",
    numberInStock: 4,
    dailyRentalRate: 3.0,
  },
  {
    _id: "16",
    title: "The Stranger",
    genre: { name: "Thriller" },
    language: "French",
    numberInStock: 6,
    dailyRentalRate: 3.5,
  },

  // Tamil Movies
  {
    _id: "17",
    title: "Mersal",
    genre: { name: "Action" },
    language: "Tamil",
    numberInStock: 10,
    dailyRentalRate: 2.0,
  },
  {
    _id: "18",
    title: "Sivaji",
    genre: { name: "Comedy" },
    language: "Tamil",
    numberInStock: 8,
    dailyRentalRate: 2.3,
  },
  {
    _id: "19",
    title: "Vinnaithaandi Varuvaayaa",
    genre: { name: "Romance" },
    language: "Tamil",
    numberInStock: 4,
    dailyRentalRate: 2.7,
  },
  {
    _id: "20",
    title: "Kaithi",
    genre: { name: "Thriller" },
    language: "Tamil",
    numberInStock: 6,
    dailyRentalRate: 3.0,
  },

  // Telugu Movies
  {
    _id: "21",
    title: "Baahubali: The Beginning",
    genre: { name: "Action" },
    language: "Telugu",
    numberInStock: 12,
    dailyRentalRate: 2.8,
  },
  {
    _id: "22",
    title: "F2: Fun and Frustration",
    genre: { name: "Comedy" },
    language: "Telugu",
    numberInStock: 5,
    dailyRentalRate: 2.5,
  },
  {
    _id: "23",
    title: "Geetha Govindam",
    genre: { name: "Romance" },
    language: "Telugu",
    numberInStock: 7,
    dailyRentalRate: 2.6,
  },
  {
    _id: "24",
    title: "Goodachari",
    genre: { name: "Thriller" },
    language: "Telugu",
    numberInStock: 6,
    dailyRentalRate: 3.0,
  },
];

export default movies;
